package com.app.config;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.web.util.matcher.AntPathRequestMatcher;


@Configuration
@EnableWebSecurity				// for security
public class SecurityConfig extends WebSecurityConfigurerAdapter {
	
	
	@Autowired
	public BCryptPasswordEncoder pwdEncoder;
	
	@Override
	protected void configure(AuthenticationManagerBuilder auth) throws Exception {
		
		auth.inMemoryAuthentication().withUser("ajay").password(pwdEncoder.encode("ajay")).authorities("ADMIN");
		auth.inMemoryAuthentication().withUser("sam").password(pwdEncoder.encode("sam")).authorities("EMP");
		auth.inMemoryAuthentication().withUser("ram").password(pwdEncoder.encode("ram")).authorities("STD");
		
	}
	
	
	@Override
	protected void configure(HttpSecurity http) throws Exception {
		
		http.authorizeRequests()
		.antMatchers("/all").permitAll()
		.antMatchers("/emp").hasAuthority("EMP")
		.antMatchers("/admin").hasAuthority("ADMIN")
		.antMatchers("/common").hasAnyAuthority("ADMIN","EMP")
		.anyRequest().authenticated()					// rest of the requests only login
		
		// login form  generated by spring framework
		.and()
		.formLogin()
		.defaultSuccessUrl("/view",true)			
		
		// for logout
		.and()
		.logout()
		.logoutRequestMatcher(new AntPathRequestMatcher("/logout"))
		.logoutSuccessUrl("/login?logout")
		
		// error page or invalid access page
		.and()
		.exceptionHandling()
		.accessDeniedPage("/denied")
		
		;
		
	}
	
}
